### PR TITLE
Skip t/07-debugger.t when PERL5DB is set

### PR DESCRIPTION
**Pull request by atoomic**
RT 127516

On a fresh perl installation, Devel::NYTProf is missing
and is not listed in TestRequires...
thus namespace::autoclean fails during unit test and cannot
be install...

List NYTProf as a recommends and skip the test if missing.

Upstream-URL: https://rt.cpan.org/Ticket/Display.html?id=127516

### CODE REVIEW

**Comment by haarg** [comment]
Are you using the PERL5DB environment variable? namespace::clean does not use NYTProf in its tests at all.

**Comment by atoomic** [comment]
@haarg argg yeap you are right, my env is set to
```
PERL5DB='use Devel::NYTProf'
```

so just need to improve the patch to check that perl -d can be loaded or maybe alternatively unset PERL5DB during the unit test...

**Comment by atoomic** [comment]
@haarg here is a better way to avoid the issue when PERL5DB is set... 
of course a better one would be to do not set PERL5DB itself lol

**Comment by atoomic** [comment]
steps to reproduce
```
PERL5DB='use Missing::Module' prove -vwl t/07-debugger.t
```

with this suggested patch it will skip the test
```
t/07-debugger.t ..
1..0 # SKIP custom ENV{PERL5DB} set.
skipped: custom ENV{PERL5DB} set.
Files=1, Tests=0,  1 wallclock secs ( 0.01 usr  0.01 sys +  0.04 cusr  0.01 csys =  0.07 CPU)
Result: NOTESTS
```

**Comment by haarg** [comment]
Fixed in 6fc5ae48ee6c9ec93b2601b96ad717ee1fc048e3 by cleaning up the environment.

**Comment by atoomic** [comment]
excellent thanks

**Pull request closed without merging**
